### ISSUE TITLE
Stuck at Welcome Page

### ISSUE THREAD

**Issue by aamirglb** [mavlink/containers#24]
I'm trying to spin of a container on Linux using the following commands:
```shell
$ git clone https://github.com/mavlink/containers.git
$ cd containers
$ docker build -t qgc_dev -f Dockerfile_qgc-build-linux .
```
but the script get stuck at Welcome Page. What I'm suppose to do at this stage?
![qgc_container](https://user-images.githubusercontent.com/15617408/115110396-45c97300-9f8c-11eb-8a1c-e44fa93859d1.png)

Thanks in advance.

**Comment by hamishwillee** [comment]
I don't think the docker containers are intended for third party use. General build instructions are here: https://dev.qgroundcontrol.com/master/en/getting_started/

If you have questions like this, suggest perhaps you try the support channels: https://dev.qgroundcontrol.com/master/en/#support
